name: Build and test on multiple platforms
run-name: 🚀 Build and Test  (${{ github.sha }})

on:
  push:
    branches:
      - dev

jobs:
  build-wheels:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, windows-2022, macos-14, ubuntu-22.04-arm ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install
        run: pip install .
        env:
          CC: ${{ matrix.os == 'ubuntu-22.04-arm' && '/usr/bin/aarch64-linux-gnu-gcc' || '' }}